### ISSUE TITLE
URL for favicon

### ISSUE THREAD

**Issue by MrRefactoring** [Drarig29/typedoc-plugin-extras#10]
Hi @Drarig29! Thanks for your plugin.

I considered adding a favicon to my docs via URL to host where SVG placed.

What do you think about this functionality?

**Comment by Drarig29** [comment]
It's almost already possible. I think we just need to not try to copy the file and simply give a URL instead of a filename.

You could also download the favicon ans specify the filename.

Do you want to make a PR?

**Comment by Drarig29** [comment]
Oh! I think I put NodeJS 15 in the dev dependencies but it's not a minimal version... you can use the plugin with lower versions of Node I think.
