### ISSUE TITLE
Use idiomatic English for footer date/time

### ISSUE THREAD

**Issue by grempe** [Drarig29/typedoc-plugin-extras#15]
The `footerDate` option currently displays something like:

`Generated using TypeDoc version 0.22.15, the 5/1/2022 at 2:53:15 PM`

This reads incorrectly in at least American English and I would suggest it should be:

`Generated using TypeDoc version 0.22.15, on 5/1/2022 at 2:53:15 PM`

https://github.com/Drarig29/typedoc-plugin-extras/blob/master/src/main.ts#L111

I would also suggest showing the time zone since you are displaying a locale specific time and not UTC otherwise it would not be possible to know in which time .

Or, even better, just remove the English prefix words and just display a locale friendly version of the full date and timestamp that is usable anywhere.

**Comment by Drarig29** [comment]
Hey! Sorry for the delay.

In this release, I just replaced `the` with `on`: https://github.com/Drarig29/typedoc-plugin-extras/releases/tag/v2.2.4

And in this 2nd release, I moved the computing of the generation date string to the client side.
So now, the local timezone and the user locale is used: https://github.com/Drarig29/typedoc-plugin-extras/releases/tag/v2.2.5

![image](https://user-images.githubusercontent.com/9317502/179236915-a1ded3c8-f619-4cf6-ad63-a64b583055e5.png)
