### ISSUE TITLE
Add Google Analytics / Tags extra

### ISSUE THREAD

**Issue by isaacyakl** [Drarig29/typedoc-plugin-extras#17]
It would be cool if you made an option to add an analytics code!

You could then create a script element and insert it into the DOM as the first child of the head element.

```html
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=THE_MEASUREMENT_ID"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'THE_MEASUREMENT_ID');
</script>
```

**Comment by Drarig29** [comment]
Good idea! Added in [v2.3.2](https://github.com/Drarig29/typedoc-plugin-extras/releases/tag/v2.3.2)
